### ISSUE TITLE
Not working on localhost

### ISSUE THREAD

**Issue by Seonnyn** [SeameX/RemoveCookiesFromDomain#2]
When trying to use it on localhost environment, it will just reload the page, but not delete the cookies.

Possible Fix: #1

**Comment by SeameX** [comment]
Hi, 
im sorry for the delayed answer i was on holidays :)
Thanks for the issue and for the fix i will test and merge today.

**Comment by SeameX** [comment]
All Toplevel domains are working now. Thanks for the Issue!
